apiVersion: v1
kind: ConfigMap
metadata:
  name: "page-index"
  labels:
    page.ctfpilot.com/slug: "index"
    page.ctfpilot.com/version: "2"
    page.ctfpilot.com/enabled: "true"
    page.ctfpilot.com/configmap: "page-config"
    challenges.ctfpilot.com/configmap: "page-config"
    ctfpilot.com/component: "page-config"
data:
  slug: "index"
  name: "index"
  path: "pages/index"
  repository: "ctfpilot/challenges-example"
  generated_at: "2025-12-20 19:01:16"
  page: |
    {
      "$schema": "https://raw.githubusercontent.com/ctfpilot/page-schema/refs/heads/main/schema.json",
      "enabled": true,
      "slug": "index",
      "title": "Index page",
      "route": "/",
      "content": "page.md",
      "format": "markdown",
      "auth": false,
      "draft": false
    }

  content: |
    # CTF Pilot index page
    
    Welcome to the demo CTF, it is running on the CTF Pilot platform!

